### ISSUE TITLE
tester composants React flexbox

### ISSUE THREAD

**Issue by abenhamdine** [Arhia/arhia-next-ui#100]
## Besoins : 
- pouvoir aligner de gauche à droite : A largeur fixe, B flex, C largeur fixe
- idem de haut en base
- pouvoir aligner de gauche à droite : A largeur fixe, B flex, C flex, B devant être 2X plus large que C
- idem de haut en bas

- mettre des composants antd dedans (buttons, ...) pour tester affichage et compatibilité
- tester plusieurs niveaux (flexbox dans flexbox)

Equivalent Extjs :  

examples.sencha.com/extjs/6.5.3/examples/kitchensink/?classic#layout-horizontal-box

## Modules trouvés  

- grid layout intégré à antdesign : ne gère pas le flex avec des colonnes de largeur fixe, ni les flex avec des poids différents (voir aussi issue ant-design/ant-design#7309)
- http://roylee0704.github.io/react-flexbox-grid/ : ne gère pas le flex avec des colonnes de largeur fixe, ni les flex avec des poids différents
- https://github.com/jxnblk/reflexbox
- https://github.com/jxnblk/grid-styled : idem reflexbox mais avec styled-components
- https://github.com/buildo/react-flexview : ne gère pas le responsive
- https://github.com/nachoaIvarez/flexbox-react : gère toutes les propriés flex mais pas le responsive donc pas d'intérêt
- https://github.com/kodyl/react-flexr : pas assez de traction

**Comment by pighqs** [comment]
issue ouverte chez ant-design à ce propos:
https://github.com/ant-design/ant-design/issues/7309

**Comment by abenhamdine** [comment]
laisser tomber react-flexr qui n'a pas assez de traction  
tester plutot https://github.com/jxnblk/reflexbox

**Comment by pighqs** [comment]
```import React, { Component } from 'react';
import './App.css';
import { Flex, Box } from 'reflexbox';
import { Row, Col, Button, Radio } from 'antd';
const RadioGroup = Radio.Group;

class Grid extends Component {

  state = {
    value: 1,
  }
  onChange = (e) => {
    console.log('radio checked', e.target.value);
    this.setState({
      value: e.target.value,
    });
  }

  render() {

    return (
      <div>
        <h2>Ant Grid</h2>
        <Row type="flex" justify='space-around' className='row'>
          <Col className='item col16' span={16}>col-16</Col>
          <Col className="item lar200px">200px</Col>
          <Col className='item col6' span={2}>col-6</Col>
        </Row>


        <h2>ReflexBox Grid</h2>
        <Flex p={0}>
          <Box className='item' px={3} w={800}></Box>
          <Box className='item' px={5} w={0.5}><RadioGroup onChange={this.onChange} value={this.state.value}>
            <Radio value={1}>Tous</Radio>
            <Radio value={2}>Aucun</Radio>
            <Radio value={3}>En attente</Radio>
          </RadioGroup></Box>
          <Box className='item' px={5} w={100}><Button>Default</Button></Box>
        </Flex>
        <Flex className='row' p={0}>
          <Box className='no-bckg item' px={5} w={800}>800px</Box>
          <Box className='no-bckg item' px={5} w={0.5}>50%</Box>
          <Box className='no-bckg item' px={5} w={100}>100px</Box>
        </Flex>

        <Flex p={0}>
          <Box className='item' px={5} w={400}>
            <RadioGroup onChange={this.onChange} value={this.state.value}>
              <Radio value={1}>Tous</Radio>
              <Radio value={2}>Aucun</Radio>
              <Radio value={3}>En attente</Radio>
            </RadioGroup>
          </Box>
          <Box className='item' px={5} w={0.5}></Box>
          <Box className='item' px={5} w={0.25}><Button>Default</Button></Box>
        </Flex>
        <Flex className='row' p={0}>
          <Box className='no-bckg item' px={5} w={400}>400px</Box>
          <Box className='no-bckg item' px={5} w={0.5}>50%</Box>
          <Box className='no-bckg item' px={5} w={0.25}>25%</Box>
        </Flex>

        <Flex column='true' p={0}>
          <Flex>
            <Box className='item' px={5} w={400}>
              <RadioGroup onChange={this.onChange} value={this.state.value}>
                <Radio value={1}>Tous</Radio>
                <Radio value={2}>Aucun</Radio>
                <Radio value={3}>En attente</Radio>
              </RadioGroup>
              <p>400px</p> 
            </Box>
          </Flex>
          <Flex>
            <Box className='item' px={5} w={0.85}>85%</Box>
            <Box className='item' px={5} w={0.25}>
            <Button>Default</Button>
            <p>25%</p>
            </Box>
          </Flex>
        </Flex>
      </div>
    );
  }
}

export default Grid;

```

**Comment by pighqs** [comment]
<img width="1678" alt="capture d ecran 2018-03-20 a 11 21 37" src="https://user-images.githubusercontent.com/24443058/37649130-3277d0d4-2c31-11e8-95f5-345137a2c953.png">
<img width="401" alt="capture d ecran 2018-03-20 a 11 21 52" src="https://user-images.githubusercontent.com/24443058/37649140-36b5e5a0-2c31-11e8-8f36-e4897eb7559e.png">

**Comment by abenhamdine** [comment]
donc c'est ok ? flexbox répond à la demande ?

**Comment by pighqs** [comment]
oui car il gère les largeurs fixes et les largeurs en pourcentage:

- le pourcentage calculé est relatif à la taille du container parent de l'item.
- En cas de container parent trop petit,  les items avec largeurs fixes ne sont pas redimensionnés, par contre les items avec largeur exprimée en % sont redimensionnés en tenant compte de l'espace restant libre une fois les items à largeur fixe décomptés de la largeur du parent.
- si un item avec une largeur en % est parent d'un item avec une largeur fixe , sa taille minimale est celle de l'item qu'il contient.

**Comment by abenhamdine** [comment]
ok merci

**Comment by abenhamdine** [comment]
je réouvre car on doit aussi tester le flex vertical (column)

**Comment by abenhamdine** [comment]
celui là gère toutes les propriétés flexbox, mais pas le responsive : 
https://github.com/nachoaIvarez/flexbox-react
